---
# action.yml
name: 'Screenly'
description: 'GitHub Actions for Screenly.'
author: 'Screenly, Inc'
branding:
  icon: 'code'
  color: 'purple'
inputs:
  screenly_api_token:
    description: "Your Screenly API token."
    required: true
  cli_commands:
    description: "Your Screenly CLI command(s)."
    required: true
  cli_version:
    description: "Screenly CLI version"
    default: "v0.1.4"
outputs:
  stdout: ${{ steps.run-cli.test }}

runs:
  using: 'composite'
  steps:
    - name: Download CLI
      id: download-cli
      run: |
        wget -q -O /tmp/screenly-cli.tar.gz \
          "https://github.com/Screenly/cli/releases/download/${{ inputs.cli_version }}/screenly-cli-x86_64-unknown-linux-gnu.tar.gz"
        cd /tmp
        tar xfz screenly-cli.tar.gz
        chmod +x screenly
      shell: bash

    - name: Run CLI
      id: run-cli
      run: |
        output=$(API_TOKEN=${{ inputs.screenly_api_token }} \
          /tmp/screenly ${{ inputs.cli_commands }})

        # Export stdout
        echo "result=$output" >> "$GITHUB_OUTPUT"

        # Print stdout
        echo "$output"
      shell: bash
