---
# action.yml
name: 'Screenly'
description: 'GitHub Actions for Screenly.'
author: 'Screenly, Inc'
branding:
  icon: 'code'
  color: 'purple'
inputs:
  screenly_api_token:
    description: "Your Screenly API token."
    required: true
  cli_commands:
    description: "Your Screenly CLI command(s)."
    required: true
  cli_version:
    description: "Screenly CLI version."
    default: "v0.2.7"
outputs:
  cli_commands_response:
    description: "The response from the Screenly CLI command(s)."
    value: ${{ steps.run-cli.outputs.response }}

runs:
  using: 'composite'
  steps:
    - name: Download CLI
      id: download-cli
      run: |
        pushd /tmp
        wget -q -O screenly-cli.tar.gz \
          "https://github.com/Screenly/cli/releases/download/${{ inputs.cli_version }}/screenly-cli-x86_64-unknown-linux-gnu.tar.gz"
        tar xfz screenly-cli.tar.gz
        chmod +x screenly
        popd
      shell: bash

    - name: Run CLI
      id: run-cli
      run: |
        set -o pipefail
        output=$(API_TOKEN=${{ inputs.screenly_api_token }} /tmp/screenly ${{ inputs.cli_commands }} | tr '\n' ' ')
        exit_code=$?
        echo "response=$output" >> "$GITHUB_OUTPUT"
        exit $exit_code
      shell: bash
