---

name: Docs

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  docs-help-md:
    permissions:
      contents: write
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Generate documentation
        run: cargo run -- print-help-markdown > /tmp/CommandLineHelp.md

      - name: Compare documentation
        run: |
          echo "Running diff command to compare documentation..."

          diff_output=$(diff /tmp/CommandLineHelp.md docs/CommandLineHelp.md)
          diff_exit_status=$?

          if [ $diff_exit_status -ne 0 ]; then
            echo "::error::$diff_output"
            echo "::error::Documentation is out of date. Please run 'cargo run -- print-help-markdown > docs/CommandLineHelp.md' and commit the changes."
          else
            echo "Documentation is up to date."
          fi

          exit $diff_exit_status
