---

name: Docs

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  docs-help-md:
    permissions:
      contents: write
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Generate documentation
        run: cargo run -- print-help-markdown > /tmp/CommandLineHelp.md

      - name: Compare documentation
        run: |
          diff_output=$(diff /tmp/CommandLineHelp.md docs/CommandLineHelp.md || true)

          if [ -n "$diff_output" ]; then
            echo "$diff_output"
            echo "::error::Documentation is out of date. Please run 'cargo run -- print-help-markdown > docs/CommandLineHelp.md' and commit the changes."
            exit 1
          else
            echo "Documentation is up to date."
          fi

      - name: Trigger Developer Portal deploy workflow
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DEVELOPER_PORTAL_REPO_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{"event_type": "deploy"}' \
            https://api.github.com/repos/Screenly/developer-portal/dispatches
