name: Rust Linting

on:
  push:
    branches:
      - master
    paths:
      - "**.rs"
      - "Cargo.toml"
      - ".github/workflows/lint.yml"
  pull_request:
    branches:
      - master
    paths:
      - "**.rs"
      - "Cargo.toml"
      - ".github/workflows/lint.yml"

permissions:
  contents: read

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies
        run: sudo apt  -q -yy install libdbus-1-dev pkg-config libdbus-1-3 libsystemd0 libsystemd-dev

      - name: Install clippy
        run: rustup component add clippy

      - name: Run clippy
        run: cargo clippy --manifest-path Cargo.toml --all-targets -- -D warnings
