name: Rust Linting

on:
  push:
    branches:
      - master
    paths:
      - "**.rs"
      - "Cargo.toml"
  pull_request:
    branches:
      - master
    paths:
      - "**.rs"
      - "Cargo.toml"

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies
        run: sudo apt  -q -yy install libdbus-1-dev pkg-config libdbus-1-3 libsystemd0 libsystemd-dev

      - name: rust-clippy-check
        uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path rust-services/Cargo.toml
