name: Lint
on:
  push:
    paths:
      - 'src/**'
      - 'Cargo.toml'

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: rust-clippy-check
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: rust-fmt-check
        uses: actions-rust-lang/rustfmt@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
