name: Nix

on:
  push:
    branches:
      - master
    paths:
      - "flake.nix"
      - "flake.lock"
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/nix.yml"
  pull_request:
    branches:
      - master
    paths:
      - "flake.nix"
      - "flake.lock"
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/nix.yml"

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout flake
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - name: Setup FlakeHub Cache
        uses: DeterminateSystems/flakehub-cache-action@3be0931021788e3bb4df65f59a555039c2fa2d46 # main

      - name: Build screenly-cli
        run: nix build .#screenly-cli
