name: Nix

on:
  push:
    branches:
      - master
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/nix.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/nix.yml'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout flake
        uses: actions/checkout@v4

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@v8

      - name: Setup FlakeHub Cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Build screenly-cli
        run: nix build .#screenly-cli
