# .github/workflows/release.yml

on:
  push:
    tags:
      - '*'

jobs:
  linux_x86:
    name: Linux x86
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Zip artifact for deployment
        run: zip screenly-cli-linux-x86.zip target/release/screenly
      - uses: actions/upload-artifact@v3
        with:
          name: Upload x86 binaries
          path: screenly-cli-linux-x86.zip
  macos_intel:
    name: Macos Intel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-apple-darwin
      - name: Zip artifact for deployment
        run: zip screenly-cli-apple-x86.zip target/x86_64-apple-darwin/release/screenly
      - uses: actions/upload-artifact@v3
        with:
          name: Upload x86 binaries
          path: screenly-cli-apple-x86.zip
  macos_arm64:
    name: Macos arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target aarch64-apple-darwin
      - name: Zip artifact for deployment
        run: zip screenly-cli-apple-arm64.zip target/release/screenly
      - uses: actions/upload-artifact@v3
        with:
          name: Upload arm64 apple binaries
          path: screenly-cli-apple-arm64.zip

