# .github/workflows/release.yml

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
      name: deploy
      runs-on: ubuntu-latest
      strategy:
        matrix:
          target: [ x86_64-unknown-linux-gnu, x86_64-apple-darwin, aarch64-apple-darwin]
      steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Install rust
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            profile: minimal
            override: true
            target: ${{ matrix.target }}

        - name: Build target
          uses: actions-rs/cargo@v1
          with:
            use-cross: true
            command: build
            args: --release --target ${{ matrix.target }}

        - name: Package
          shell: bash
          run: |
            #strip target/${{ matrix.target }}/release/testmest
            cd target/${{ matrix.target }}/release          
            tar czvf ../../../screenly-cli-${{ matrix.target }}.tar.gz screenly
            cd -
        - name: Publish
          uses: softprops/action-gh-release@v1
          # TODO: if any of the build step fails, the release should be deleted.
          with:
              files: 'screenly*'
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}