name: Rust

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'Cargo.toml'
  pull_request:
    branches:
      - master
    paths:
      - 'src/**'
      - 'Cargo.toml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - uses: actions/upload-artifact@v3
        with:
          name: Upload build
          path: cli/target/debug/screenly
