---
name: Generate SBOMs

on:
  push:
    branches:
      - master
    paths:
      - 'Cargo.lock'

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install sbom4rust
        run: |
          pip install git+https://github.com/anthonyharrison/sbom4rust.git

      - name: Run sbom4rust
        run: |
          sbom4rust -a screenly-cli --sbom spdx --format json -o sbom.spdx.json
          sbom4rust -a screenly-cli --sbom cyclonedx --format json -o sbom.cyclonedx.json

      - name: Upload SPDX SBOM
        uses: actions/upload-artifact@v3
        with:
          name: cli-SPDX
          path: sbom.spdx.json

      - name: Upload CycloneDX SBOM
        uses: actions/upload-artifact@v3
        with:
          name: cli-CycloneDX
          path: sbom.cyclonedx.json
