---
name: Generate SBOMs

on:
  push:
    tags:
      - 'v*'

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install cyclonedx-rust-cargo
        run: |
          cargo install cargo-cyclonedx

      - name: Generate SBOM
        run: |
          cargo cyclonedx \
            --spec-version 1.5 \
            -f json

      - name: Enrich and clean up SBOM
        run: |

          # Grab the version
          export VERSION_TAG="${GITHUB_REF#refs/*/}"
          export VERION=$(echo $VERSION_TAG | sed 's/^v//g')

          # Delete unnecessary metadata.component.components and
          # set GITHUB_RUN_NUMBER as the version of the SBOM
          jq 'del(.metadata.component.components) | .version = (env.GITHUB_RUN_NUMBER | tonumber)' \
            screenly.cdx.json \
            > screenly.cdx.json.tmp
          mv screenly.cdx.json.tmp screenly.cdx.json

          # Render SBOM metadata template
          cat sbom/metadata.cdx.json.tmpl | jq | \
            envsubst > metadata.cdx.json

          # Merge in CycloneDX Metadata
          jq --slurp '.[0] * .[1]' \
            screenly.cdx.json \
            metadata.cdx.json \
            > screenly-cli.cdx.json

      - name: Upload CycloneDX SBOM
        uses: actions/upload-artifact@v3
        with:
          name: cli-CycloneDX
          path: screenly-cli.cdx.json

      - name: Upload SBOM
        uses: sbomify/github-action@master
        with:
          token: ${{ secrets.SBOMIFY_TOKEN }}
          sbom-file: 'screenly-cli.cdx.json'
