---
name: Generate SBOMs

on:
  push:
    tags:
      - 'v*'

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload SBOM
        uses: sbomify/github-action@master
        env:
          TOKEN: ${{ secrets.SBOMIFY_TOKEN }}
          COMPONENT_ID: 'UUzAdk8ixV'
          LOCK_FILE: 'Cargo.lock'
          AUGMENT: false
          ENRICH: true
